# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-22 09:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Moreinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('phone_no', models.CharField(max_length=13)),
                ('country', models.CharField(blank='True', max_length=100)),
                ('dob', models.DateField(default='1980-01-01')),
            ],
        ),
    ]
