# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-23 18:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Moreinfo',
        ),
    ]
