# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-25 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profili', '0002_remove_profile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], default='M', max_length=2),
        ),
        migrations.AlterField(
            model_name='profile',
            name='dob',
            field=models.DateTimeField(default=None),
        ),
    ]
