# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-25 16:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profili', '0005_auto_20200425_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dob',
            field=models.DateField(default='1980-01-01'),
        ),
    ]
