# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-25 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profili', '0006_auto_20200425_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='profile',
            name='prof',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
