# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-25 19:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profili', '0007_auto_20200425_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, upload_to=b'', verbose_name='Profile Pic'),
        ),
    ]
